version: '3'

services:
  nginxContainerService:
    container_name: nginxContainerService
    env_file:
      - ./.env
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx-templates:/etc/nginx/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbotContainerService:
    container_name: certbotContainerService
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
